### ISSUE TITLE
Hi, how can i set output dim?

### ISSUE THREAD

**Issue by Wooks-git** [d246810g2000/tensorrt#4]
i trained with 3 classes with my custom dataset and based nanodet-m.
i set parser
--outputs '787[1,3,40,40], 788[1,32,40,40], 809[1,3,20,20], 810[1,32,20,20], 831[1,3,10,10], 832[1,32,10,10]' 
is it right?

**Comment by d246810g2000** [comment]
> i trained with 3 classes with my custom dataset and based nanodet-m.
> 
> i set parser
> 
> --outputs '787[1,3,40,40], 788[1,32,40,40], 809[1,3,20,20], 810[1,32,20,20], 831[1,3,10,10], 832[1,32,10,10]' 
> 
> is it right?

You need to put the onnx file you exported into netron to view network structure, and then modify it by onnx_edit.py.  In addition, you can try yolox, it has very good support for tensorrt, I believe you will save a lot of trouble.

**Comment by Wooks-git** [comment]
really appreciate your answer! i fix my error.
but i have one more error.
when i run trt_demo.py , 

Traceback (most recent call last):
  File "demo/trt_demo.py", line 195, in <module>
    main()
  File "demo/trt_demo.py", line 168, in main
    meta, res = predictor.inference(frame)
  File "demo/trt_demo.py", line 91, in inference
    results = self.model.head.post_process((cls_scores, bbox_preds), meta)
  File "/home/dinsight/nanodet/nanodet/model/head/gfl_head.py", line 549, in post_process
    for result, img_width, img_height, img_id, warp_matrix in zip(result_list, img_widths,img_heights, img_ids, warp_matrixes):
TypeError: zip argument #2 must support iteration

got this error...

do you know how to fix it?

**Comment by d246810g2000** [comment]
> really appreciate your answer! i fix my error. but i have one more error. when i run trt_demo.py ,
> 
> Traceback (most recent call last): File "demo/trt_demo.py", line 195, in main() File "demo/trt_demo.py", line 168, in main meta, res = predictor.inference(frame) File "demo/trt_demo.py", line 91, in inference results = self.model.head.post_process((cls_scores, bbox_preds), meta) File "/home/dinsight/nanodet/nanodet/model/head/gfl_head.py", line 549, in post_process for result, img_width, img_height, img_id, warp_matrix in zip(result_list, img_widths,img_heights, img_ids, warp_matrixes): TypeError: zip argument #2 must support iteration
> 
> got this error...
> 
> do you know how to fix it?

I don’t know, you may need to check the code line by line.
